name: "Deploy CodigoFacilito"

on:
  push:
    branches: ["master"]

josb:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      run: echo "Hacemos pull del Codigo"
      run: echo "Correr Migraciones"
      run: echo "Generar Binario"
      run: echo "Publicar Version"
      